# SonarQube — java-microservice-gateway
sonar.projectKey=java-microservice-gateway
sonar.projectName=java-microservice-gateway
sonar.projectVersion=1.0.0-SNAPSHOT

sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.exclusions=**/target/**
