# SonarQube — java-microservice-common
sonar.projectKey=java-microservice-common
sonar.projectName=java-microservice-common
sonar.projectVersion=1.0.0-SNAPSHOT

sonar.host.url=http://localhost:9000

sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.modules=common-core,common-cloud-starter
common-core.sonar.projectName=common-core
common-cloud-starter.sonar.projectName=common-cloud-starter

sonar.coverage.jacoco.xmlReportPaths=common-core/target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**
